{% set name = "helixer" %}
{% set version = "0.3.1" %}
{% set sha256 = "5cf983f320f5255656b9999895c84afdbfd3546ce299955cf3bf44c41f9cb0cd" %}

package:
  name: {{ name|lower}}
  version: {{ version }}

source:
  url: https://github.com/weberlab-hhu/Helixer/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0

requirements:
  - python =3.8
  - seaborn
  - Keras
  - terminaltables
  - numpy
  - h5py
  - sqlalchemy =1.3.22
  - cudatoolkit =11.5
  - tensorflow-gpu =2.7.0
  - nni # missing on conda : en attente packahe conda créer + PR

test:
  imports:
    - pytest
    - requests

  commands:
    - ./target/release/helixer_post_bin

buil:
  skip: true

about:
  home: https://github.com/weberlab-hhu/Helixer
  license: MIT
  license_file: LICENSE
  summary: "Helixer is a tool for configuring and training models for 
  de novo gene structure prediction."